import { Metadata } from 'next';
import { Suspense } from 'react';
import HeaderCrecWrapper from '@/components/header-crec/HeaderCrecWrapper';
import FooterCrecWrapper from '@/components/footer-crec/FooterCrecWrapper';
import ServicesCrecWrapper from '@/components/services-crec/ServicesCrecWrapper';

export const metadata: Metadata = {
  title: 'Nos Services',
  description: "",
};

export default function NosServicesPage() {
  return (
    <div className="min-h-screen bg-background">
      <Suspense fallback={null}>
        <HeaderCrecWrapper {...{ "contactTextColor": "#FFFFFF", "navTextColor": "#243B76", "fontFamily": "Inter", "mediaUrl1": "https://majoli-hub-images-s3.s3.eu-north-1.amazonaws.com/header-crec--mediaUrl1-1770740288481-mplmp50o02m.png", "mediaAlt1": "Logo", "mediaType1": "image", "logoText": "JREJ", "logoSubtext": "EXPERTS COMPTABLES", "phoneNumber": "(+216) 71 78 40 07", "email": "s.bmansour@cabinet-amci.com", "link1Text": "Accueil", "link1Href": "/", "link2Text": "Nos services", "link2Href": "/nos-services", "link3Text": "Actualités", "link3Href": "/actualites", "link4Text": "Nous sommes", "link4Href": "/qui-sommes-nous", "ctaButtonText": "Nous contacter", "ctaButtonHref": "/contact", "buttonGradientStart": "#1E3A5F", "buttonGradientEnd": "#2E5A8A", "buttonTextColor": "#FFFFFF", "activeLinkUnderlineColor": "#243B76", "mediaUrl0": "" }} />
    <FooterCrecWrapper {...{ "backgroundColor": "#E5E7EB", "contentBlockBg": "#FFFFFF", "headingColor": "#243B76", "linkColor": "#243B76", "inputBg": "#E8E8E8", "inputTextColor": "#33363B", "inputPlaceholderColor": "#555C66", "buttonBg": "#1A2D5C", "buttonTextColor": "#FFFFFF", "buttonGradientStart": "#1A2D5C", "buttonGradientEnd": "#2E4A7C", "copyrightColor": "#9CA3AF", "fontFamily": "Inter", "mediaUrl1": "https://majoli-hub-images-s3.s3.eu-north-1.amazonaws.com/footer-crec--mediaUrl1-1770740269152-6t01zw4rrq5.png", "mediaAlt1": "Logo", "mediaType1": "image", "logoText": "CREJ", "logoSubtext": "EXPERTS COMPTABLES", "navSectionTitle": "Navigations", "link1Text": "Accueil", "link1Href": "/", "link2Text": "Nos Services", "link2Href": "/nos-services", "link3Text": "Actualités", "link3Href": "/actualites", "link4Text": "Nous sommes", "link4Href": "/nous-sommes", "link5Text": "Nous contacter", "link5Href": "/contact", "legalSectionTitle": "Liens légaux", "legalLink1Text": "Politique de confidentialité", "legalLink1Href": "/politique-de-confidentialite", "legalLink2Text": "Mentions légales", "legalLink2Href": "/mentions-legales", "legalLink3Text": "Termes et conditions", "legalLink3Href": "/termes-et-conditions", "socialSectionTitle": "Réseaux Sociaux", "social1Url": "", "social2Url": "", "social3Url": "", "newsletterTitle": "Inscrivez-vous pour connaître les dernières nouveautés", "newsletterDescription": "Inscrivez-vous à notre newsletter pour ne pas rater nos offres exclusives.", "inputNamePlaceholder": "Jacques DUPONT", "inputEmailPlaceholder": "mail@mail.com", "newsletterButtonText": "S'inscrire à la newsletter", "copyrightText": "Copyright 2026 CREC Tous droits réservés.", "creditText": "Made By Majoli.io with ❤️", "mediaUrl0": "" }} />
    <ServicesCrecWrapper {...{ "fontFamily": "Inter", "title": "Gestion Sociale & RH : Valorisez votre capital humain.", "subtitle": "La gestion des salariés est l'un des aspects les plus complexes pour un dirigeant. Notre pôle social prend en charge l'intégralité du cycle de vie de vos collaborateurs. De l'embauche avec la rédaction des contrats de travail à la sortie du salarié, nous sécurisons chaque étape juridique. Nous réalisons vos bulletins de paie avec une précision rigoureuse et télé-déclarons l'ensemble de vos cotisations sociales (Urssaf, retraites, prévoyance). Au-delà de l'administratif, nous vous conseillons sur votre stratégie RH et l'optimisation des rémunérations pour fidéliser vos talents.", "titleColor": "#1A2D5C", "subtitleColor": "#333333", "cardBgColor": "#FFFFFF", "cardBorderColor": "#E5E7EB", "cardTitleColor": "#1A2D5C", "cardDescriptionColor": "#333333", "iconBgColor": "#1A2D5C", "iconColor": "#FFFFFF", "mediaUrl1": "", "mediaAlt1": "Icône Paie", "mediaType1": "image", "mediaUrl2": "", "mediaAlt2": "Icône Contrats", "mediaType2": "image", "mediaUrl3": "", "mediaAlt3": "Icône Audit", "mediaType3": "image", "mediaUrl4": "", "mediaAlt4": "Icône Conseil", "mediaType4": "image", "card1Title": "Paie & Déclarations", "card1Description": "Bulletins de paie conformes et télédéclarations sociales automatisées.", "card2Title": "Contrats de travail", "card2Description": "Rédaction et sécurisation juridique de tous vos contrats.", "card3Title": "Audit social", "card3Description": "Diagnostic complet de votre conformité sociale et RH.", "card4Title": "Conseil en droit du travail", "card4Description": "Accompagnement stratégique sur vos décisions RH complexes." }} />
      </Suspense>
    </div>
  );
}