import { Metadata } from 'next';
import { Suspense } from 'react';
import HeaderCrecWrapper from '@/components/header-crec/HeaderCrecWrapper';
import BlogMainPageWrapper from '@/components/blog-main-page/BlogMainPageWrapper';
import FooterCrecWrapper from '@/components/footer-crec/FooterCrecWrapper';

export const metadata: Metadata = {
  title: 'Actualité',
  description: "",
};

export default function ActualitPage() {
  return (
    <div className="min-h-screen bg-background">
      <Suspense fallback={null}>
        <HeaderCrecWrapper {...{ "contactTextColor": "#FFFFFF", "navTextColor": "#243B76", "fontFamily": "Inter", "mediaUrl1": "https://majoli-hub-images-s3.s3.eu-north-1.amazonaws.com/header-crec--mediaUrl1-1770739690145-4eegyknofsn.png", "mediaAlt1": "Logo", "mediaType1": "image", "logoText": "JREJ", "logoSubtext": "EXPERTS COMPTABLES", "phoneNumber": "(+216) 71 78 40 07", "email": "s.bmansour@cabinet-amci.com", "link1Text": "Accueil", "link1Href": "/", "link2Text": "Nos services", "link2Href": "/nos-services", "link3Text": "Actualités", "link3Href": "/actualites", "link4Text": "Nous sommes", "link4Href": "/nous-sommes", "ctaButtonText": "Nous contacter", "ctaButtonHref": "/contact", "buttonGradientStart": "#1E3A5F", "buttonGradientEnd": "#2E5A8A", "buttonTextColor": "#FFFFFF", "activeLinkUnderlineColor": "#243B76", "mediaUrl0": "" }} />
    <BlogMainPageWrapper {...{ "primaryColor": "#243B76", "secondaryColor": "#F9FAFB", "textColor": "#374151", "titleColor": "#243B76", "fontFamily": "serif", "secondaryFontFamily": "Poppins", "title": "Blog", "subtitle": "Découvrez nos derniers articles sur le droit pénal et la défense juridique", "useApi": true, "limit": 12, "article-0CtaText": "Lire l'article", "article-0Image": "h", "article-0Summary": "", "article-0Title": "Taux de rebond : pourquoi 90 % des visiteurs fuient votre site en 3 secondes", "article-0Url": "", "article-10CtaText": "Lire l'article", "article-10Image": "h", "article-10Summary": "", "article-10Title": "Avocats & Notaires : votre site web est votre première plaidoirie", "article-10Url": "", "article-11CtaText": "Lire l'article", "article-11Image": "h", "article-11Summary": "", "article-11Title": "Pourquoi choisir une pâtisserie moins sucrée ? Les secrets de Mam’zelle Flo à Lambesc.", "article-11Url": "", "article-1CtaText": "Lire l'article", "article-1Image": "h", "article-1Summary": "", "article-1Title": "Majoli.io vs plateformes freelance : pourquoi l’accompagnement bat le prix", "article-1Url": "", "article-2CtaText": "Lire l'article", "article-2Image": "h", "article-2Summary": "", "article-2Title": "Agences immobilières : automatisez vos estimations pour gagner 2 soirs par semaine", "article-2Url": "", "article-3CtaText": "Lire l'article", "article-3Image": "h", "article-3Summary": "", "article-3Title": "Les bien faits de l'alimentation sur notre corps", "article-3Url": "", "article-4CtaText": "Lire l'article", "article-4Image": "h", "article-4Summary": "", "article-4Title": "Pourquoi un site à 500 € finit toujours par coûter 5 000 € à terme", "article-4Url": "", "article-5CtaText": "Lire l'article", "article-5Image": "h", "article-5Summary": "", "article-5Title": "test", "article-5Url": "", "article-6CtaText": "Lire l'article", "article-6Image": "h", "article-6Summary": "", "article-6Title": "Marseille : Pourquoi votre concurrent apparaît sur Google Maps et pas vous ?", "article-6Url": "", "article-7CtaText": "Lire l'article", "article-7Image": "h", "article-7Summary": "", "article-7Title": "Test luxiko", "article-7Url": "", "article-8CtaText": "Lire l'article", "article-8Image": "h", "article-8Summary": "", "article-8Title": "L’Art de la Personnalisation à Aubagne : Gravure, Textile et Cadeaux sur Mesure", "article-8Url": "", "article-9CtaText": "Lire l'article", "article-9Image": "h", "article-9Summary": "", "article-9Title": "Site lent : chaque seconde de chargement vous coûte 7 % de conversion", "article-9Url": "", "mediaUrl0": "" }} />
    <FooterCrecWrapper {...{ "backgroundColor": "#f9fafb", "contentBlockBg": "#FFFFFF", "headingColor": "#243B76", "linkColor": "#243B76", "inputBg": "#E8E8E8", "inputTextColor": "#33363B", "inputPlaceholderColor": "#555C66", "buttonBg": "#1A2D5C", "buttonTextColor": "#FFFFFF", "buttonGradientStart": "#243B76", "buttonGradientEnd": "#2E4A7C", "copyrightColor": "#9CA3AF", "fontFamily": "Inter", "mediaUrl1": "https://majoli-hub-images-s3.s3.eu-north-1.amazonaws.com/footer-crec--mediaUrl1-1770739477633-7srv4ecotmd.png", "mediaAlt1": "Logo", "mediaType1": "image", "logoText": "CREJ", "logoSubtext": "EXPERTS COMPTABLES", "navSectionTitle": "Navigations", "link1Text": "Accueil", "link1Href": "/", "link2Text": "Nos Services", "link2Href": "/nos-services", "link3Text": "Actualités", "link3Href": "/actualites", "link4Text": "Nous sommes", "link4Href": "/nous-sommes", "link5Text": "Nous contacter", "link5Href": "/contact", "legalSectionTitle": "Liens légaux", "legalLink1Text": "Politique de confidentialité", "legalLink1Href": "/politique-de-confidentialite", "legalLink2Text": "Mentions légales", "legalLink2Href": "/mentions-legales", "legalLink3Text": "Termes et conditions", "legalLink3Href": "/termes-et-conditions", "socialSectionTitle": "Réseaux Sociaux", "social1Url": "", "social2Url": "", "social3Url": "", "newsletterTitle": "Inscrivez-vous pour connaître les dernières nouveautés", "newsletterDescription": "Inscrivez-vous à notre newsletter pour ne pas rater nos offres exclusives.", "inputNamePlaceholder": "Jacques DUPONT", "inputEmailPlaceholder": "mail@mail.com", "newsletterButtonText": "S'inscrire à la newsletter", "copyrightText": "Copyright 2026 CREC Tous droits réservés.", "creditText": "Made By Majoli.io with ❤️", "mediaUrl0": "" }} />
      </Suspense>
    </div>
  );
}