import { Metadata } from 'next';
import { Suspense } from 'react';
import HeaderCrecWrapper from '@/components/header-crec/HeaderCrecWrapper';
import HeroCrecWrapper from '@/components/hero-crec/HeroCrecWrapper';
import ExpertiseCrecWrapper from '@/components/expertise-crec/ExpertiseCrecWrapper';
import PhoneCrecWrapper from '@/components/phone-crec/PhoneCrecWrapper';
import AvisCuisineWrapper from '@/components/avis-cuisine/AvisCuisineWrapper';
import FooterCrecWrapper from '@/components/footer-crec/FooterCrecWrapper';

export const metadata: Metadata = {
  title: "CREC Experts Comptables",
  description: "Pilotez votre entreprise avec sérénité grâce à un accompagnement stratégique, humain et digital."
};

export default function AccueilPage() {
  return (
    <div className="min-h-screen bg-background">
      <Suspense fallback={null}>
        <HeaderCrecWrapper {...{ "contactTextColor": "#FFFFFF", "navTextColor": "#1E3A5F", "fontFamily": "Inter", "mediaUrl1": "https://majoli-hub-images-s3.s3.eu-north-1.amazonaws.com/header-crec--mediaUrl1-1770729764737-v1vd5foaie.png", "mediaAlt1": "Logo", "mediaType1": "image", "logoText": "CREC", "logoSubtext": "EXPERTS COMPTABLES", "phoneNumber": "(+216) 71 78 40 07", "email": "s.bmansour@cabinet-amci.com", "link1Text": "Accueil", "link1Href": "/", "link2Text": "Nos services", "link2Href": "/nos-services", "link3Text": "Actualités", "link3Href": "/actualites", "link4Text": "Nous sommes", "link4Href": "/nous-sommes", "ctaButtonText": "Nous contacter", "ctaButtonHref": "/contact", "buttonGradientStart": "#1E3A5F", "buttonGradientEnd": "#2E5A8A", "buttonTextColor": "#FFFFFF", "activeLinkUnderlineColor": "#243B76", "mediaAlt0": "", "mediaType0": "image", "mediaUrl0": "" }} />
    <HeroCrecWrapper {...{ "textColor": "#FFFFFF", "fontFamily": "Inter", "backgroundOverlayColor": "#1E3A5F", "backgroundOverlayOpacity": "0.4", "mediaUrl1": "https://majoli-hub-images-s3.s3.eu-north-1.amazonaws.com/hero-crec--mediaUrl1-1770719628316-8mecgcoxtl.png", "mediaAlt1": "Fond hero", "mediaType1": "image", "mediaUrl2": "https://majoli-hub-images-s3.s3.eu-north-1.amazonaws.com/hero-crec--mediaUrl2-1770719628159-lei7e71xg5.png", "mediaAlt2": "Décor deux demi-cercles", "mediaType2": "image", "title": "L'expertise comptable au service de votre ambition.", "subtitle": "Pilotez votre entreprise avec sérénité grâce à un accompagnement stratégique, humain et digital.", "ctaPrimaryText": "Prendre rendez-vous avec un expert", "ctaPrimaryHref": "/contact", "ctaSecondaryText": "Voir nos services", "ctaSecondaryHref": "/nos-services", "buttonSecondaryBorderColor": "rgba(255,255,255,0.6)", "buttonSecondaryTextColor": "#FFFFFF", "buttonGradientStart": "#1E3A5F", "buttonGradientEnd": "#2E5A8A", "mediaAlt0": "", "mediaType0": "image", "mediaUrl0": "" }} />
    <ExpertiseCrecWrapper {...{ "backgroundColor": "#f9fafb", "titleColor": "#001F5C", "title": "Notre expertise au service de votre croissance", "fontFamily": "Inter", "cardContentBg": "#243b76", "cardTextColor": "#FFFFFF", "buttonBg": "#FFFFFF", "buttonIconColor": "#284D8F", "imagePlaceholderBg": "#E5E7EB", "mediaUrl1": "https://majoli-hub-images-s3.s3.eu-north-1.amazonaws.com/expertise-crec--mediaUrl1-1770732620834-hdclx3alddc.png", "mediaAlt1": "Expertise Comptable", "mediaType1": "image", "mediaUrl2": "https://majoli-hub-images-s3.s3.eu-north-1.amazonaws.com/expertise-crec--mediaUrl2-1770732625147-35fezwcqknk.png", "mediaAlt2": "Accompagnement Juridique", "mediaType2": "image", "mediaUrl3": "https://majoli-hub-images-s3.s3.eu-north-1.amazonaws.com/expertise-crec--mediaUrl3-1770732629578-3ahxia0x5vb.png", "mediaAlt3": "Gestion sociale", "mediaType3": "image", "card1Title": "Expertise Comptable", "card1Description": "Nous gérons vos comptes et vos impôts. Vous avez l'esprit tranquille et une comptabilité toujours en règle. Concentrez-vous sur l'essentiel : la croissance de votre entreprise.", "card1Href": "/nos-services", "card1BandId": "", "card2Title": "Accompagnement Juridique", "card2Description": "Nous vous aidons pour toutes les formalités de votre société, de la création aux contrats, pour protéger votre activité. Profitez d'un conseil sur mesure pour sécuriser chacun de vos engagements.", "card2Href": "/nos-services", "card2BandId": "", "card3Title": "Gestion sociale", "card3Description": "Nous nous occupons des fiches de paie et de vos salariés. Vous gagnez du temps sur toute la partie administrative. Garantissez la conformité de vos déclarations et le respect du droit du travail.", "card3Href": "/nos-services", "card3BandId": "", "mediaUrl0": "", "mediaAlt0": "", "mediaType0": "image" }} />
    <PhoneCrecWrapper {...{ "fontFamily": "Inter", "title1": "Besoin d'un conseil ?", "title2": "Entrez votre numéro et on s'occupe du reste.", "subtitle": "Un expert vous recontacte dans les plus brefs délais", "title1Color": "#FFFFFF", "title2Color": "#FFFFFF", "subtitleColor": "#FFFFFF", "backgroundColor": "#1E3A5F", "inputPlaceholderName": "Nom", "inputPlaceholderPhone": "(+216) 71 324 567", "inputBgColor": "#E8E8E8", "buttonArrowColor": "#2C4270", "mediaUrl1": "https://majoli-hub-images-s3.s3.eu-north-1.amazonaws.com/phone-crec--mediaUrl1-1770904557874-7m7hvd7ethc.png", "mediaAlt1": "Fond bandeau conseil", "mediaUrl0": "" }} />
    <AvisCuisineWrapper {...{ "backgroundColor": "#f9fafb", "cardTypeAColor": "", "cardTypeBColor": "", "buttonBackgroundColor": "", "buttonTextColor": "", "textColor": "", "textOnDarkColor": "", "starColorOnLight": "", "starColorOnDark": "", "arrowColor": "#1A1A1A", "fontFamily": "Inter", "secondaryFontFamily": "Bodoni", "titleFontFamily": "Outfit", "titleFontFamilySecond": "Outfit", "titleText": "Nos Avis Client", "googleBadgeText": "Noté 5/5 sur", "reviewsCountText": "Basé sur 35 avis", "partnersTitle": "Nos entreprises partenaires qui nous font confiance", "reviews": [{"id":1,"name":"Stéphane LERICHE","text":"Merci pour la rénovation complète de ma salle de bain. Travaux excellents, équipe très sympathique, produits de qualité et tarif correct. Je suis très content depuis que j'ai cette belle salle de bain. Merci.","rating":5,"cardType":"A"},{"id":2,"name":"Marie DUPONT","text":"Excellente expérience avec cette équipe. Rénovation de cuisine impeccable, respect des délais et conseils précieux. Je recommande vivement !","rating":5,"cardType":"B"},{"id":3,"name":"Pierre MARTIN","text":"Travaux de très grande qualité, équipe professionnelle et à l'écoute. Le résultat final dépasse nos attentes. Merci pour ce beau travail !","rating":5,"cardType":"A"}], "partners": [{"id":1,"name":"Miele","logoUrl":"","logoAlt":"Logo Miele"},{"id":2,"name":"PORCELANOSA","logoUrl":"","logoAlt":"Logo PORCELANOSA"},{"id":3,"name":"agensia","logoUrl":"","logoAlt":"Logo agensia"},{"id":4,"name":"ESPACE Aubade","logoUrl":"","logoAlt":"Logo ESPACE Aubade"}], "mediaUrl1": "", "mediaAlt1": "Logo Google", "mediaType1": "image", "buttonText": "Laissez un avis", "buttonHref": "#", "dataSource": "mock", "apiKey": "", "placeId": "", "reviewsLimit": "20", "ratingValue": "5", "ratingCount": "35", "mediaUrl0": "" }} />
    <FooterCrecWrapper {...{ "backgroundColor": "#f9fafb", "contentBlockBg": "#FFFFFF", "headingColor": "#1A2D5C", "linkColor": "#555C66", "inputBg": "#E8E8E8", "inputTextColor": "#33363B", "inputPlaceholderColor": "#555C66", "buttonBg": "#1A2D5C", "buttonTextColor": "#FFFFFF", "buttonGradientStart": "#1A2D5C", "buttonGradientEnd": "#2E4A7C", "copyrightColor": "#9CA3AF", "fontFamily": "Inter", "mediaUrl1": "https://majoli-hub-images-s3.s3.eu-north-1.amazonaws.com/footer-crec--mediaUrl1-1770730406600-i9tzfwpafg.png", "mediaAlt1": "Logo", "mediaType1": "image", "logoText": "CREJ", "logoSubtext": "EXPERTS COMPTABLES", "navSectionTitle": "Navigations", "link1Text": "Accueil", "link1Href": "/", "link2Text": "Nos Services", "link2Href": "/nos-services", "link3Text": "Actualités", "link3Href": "/actualites", "link4Text": "Nous sommes", "link4Href": "/nous-sommes", "link5Text": "Nous contacter", "link5Href": "/contact", "legalSectionTitle": "Liens légaux", "legalLink1Text": "Politique de confidentialité", "legalLink1Href": "/politique-de-confidentialite", "legalLink2Text": "Mentions légales", "legalLink2Href": "/mentions-legales", "legalLink3Text": "Termes et conditions", "legalLink3Href": "/termes-et-conditions", "socialSectionTitle": "Réseaux Sociaux", "social1Url": "", "social2Url": "", "social3Url": "", "newsletterTitle": "Inscrivez-vous pour connaître les dernières nouveautés", "newsletterDescription": "Inscrivez-vous à notre newsletter pour ne pas rater nos offres exclusives.", "inputNamePlaceholder": "Jacques DUPONT", "inputEmailPlaceholder": "mail@mail.com", "newsletterButtonText": "S'inscrire à la newsletter", "copyrightText": "Copyright 2026 CREC Tous droits réservés.", "creditText": "Made By Majoli.io with ❤️", "mediaAlt0": "", "mediaType0": "image", "mediaUrl0": "" }} />
      </Suspense>
    </div>
  );
}